included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Tests
line_length: 160
force_try:
  severity: warning # explicitly
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
identifier_name:
  excluded: # excluded via string array
    - id
